version: '3.8'
services:
  ml-api:
    build: .
    image: ml-simple-regression:latest
    container_name: ml_fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - ./api.py:/app/api.py
      - ./data:/app/data
    command: uvicorn api:app --host 0.0.0.0 --port 8000