### Kiểm tra API dự đoán khí thải CO2 với mẫu xe 2.4L và 25 MPG
POST http://localhost:8000/co2prediction
Content-Type: application/json

{
  "ENGINESIZE": 2.4,
  "FUELCONSUMPTION_COMB_MPG": 25.0
}

###

### Kiểm tra dự đoán với xe bán tải cỡ lớn (Engine 5.3L, 15 MPG)
POST http://localhost:8000/co2prediction
Content-Type: application/json

{
  "ENGINESIZE": 5.3,
  "FUELCONSUMPTION_COMB_MPG": 15.0
}

#curl -X POST http://localhost:8000/co2prediction -H "Content-Type: application/json" -d '{"ENGINESIZE": 2.4, "FUELCONSUMPTION_COMB_MPG": 25.0}'

curl -X POST "http://127.0.0.1:8000/gd-co2-prediction" \
     -H "Content-Type: application/json" \
     -d '{
           "ENGINESIZE": 2.4,
           "CYLINDERS": 4,
           "FUELCONSUMPTION_COMB": 9.2
         }'