version: '3.8'
services:
  ml-regression:
    build: .
    image: ml-simple-regression:latest
    container_name: ml_multi_regression_runner
    volumes:
      - ./app.py:/app/app.py
      - ./data:/app/data